import os
import time
from playsound import playsound

class color:
    Normal = '\033[0;37;40m'
    Yellow = '\033[1;33;40m'
    Magenta = '\033[1;35;40m'
    Cyan = '\033[1;36;40m'

def main():
    playsound('musik.mp3', block = False)
    os.system("cls")

    time.sleep(2.5)
    print (color.Yellow + "BILA")
    time.sleep(0.3)
    print ("      DIA")
    time.sleep(0.5)
    print ("           MENYUKAIKU")
    time.sleep(1.3)
    print ("                       MENYUKAI")
    time.sleep(1)
    print ("                                 MENYUKAI")
    time.sleep(0.7)
    print (color.Cyan + "                            A")
    time.sleep(0.2)
    print ("                        A")
    time.sleep(0.2)
    print ("                    A")
    time.sleep(0.2)
    print ("                A")
    time.sleep(0.2)
    print ("            A")
    time.sleep(0.2)
    print ("        A")
    time.sleep(0.5)
    print (color.Magenta + "           AISAH")
    time.sleep(0.3)
    print ("                  TAK")
    time.sleep(0.3)
    print ("                       ADA")
    time.sleep(0.5)
    print ("                            UDANG")
    time.sleep(0.7)
    print ("                                   DIBALIK")
    time.sleep(1.5)
    print (color.Cyan + "                             BATU")
    time.sleep(0.7)
    print ("                         KA")
    time.sleep(0.3)
    print ("                     KA")
    time.sleep(0.2)
    print ("                 KA")
    time.sleep(0.1)
    print ("           KAMU")
    time.sleep(0.3)
    print (color.Yellow + "                 TERCIDUK")
    time.sleep(0.5)
    print ("                           HUJAN")
    time.sleep(0.5)
    print ("                                  BADAI")
    time.sleep(0.5)
    print ("                                         ANGIN")
    time.sleep(0.3)
    print (color.Magenta + "                                    AKU")
    time.sleep(0.5)
    print ("                             SALAH")
    time.sleep(0.5)
    print ("                        DIA")
    time.sleep(0.5)
    print ("                DEKATIKU")
    time.sleep(0.7)
    print ("          TANPA")
    time.sleep(0.7)
    print (color.Yellow + "                 MERASA")
    time.sleep(0.7)
    print ("                         BOSAN")
    time.sleep(0.5)
    print ("                                OH...")
    time.sleep(1)
    print ("                                       MY...")
    time.sleep(1)
    print ("                                              LA...")
    time.sleep(0)
    print (color.Cyan + "                            A")
    time.sleep(0.2)
    print ("                        A")
    time.sleep(0.2)
    print ("                    A")
    time.sleep(0.2)
    print ("                A")
    time.sleep(0.2)
    print ("            A")
    time.sleep(0.2)
    print ("        A")
    time.sleep(0.2)
    print ("            A")
    time.sleep(0.2)
    print ("                A")
    time.sleep(0.2)
    print ("                    A")
    time.sleep(0.2)
    print ("                        A")
    time.sleep(0.2)
    print ("                            A")
    time.sleep(0.2)
    print ("                        A")
    time.sleep(0.2)
    print ("                    A")
    time.sleep(0.2)
    print ("                A")
    time.sleep(0.2)
    print ("            A")
    time.sleep(0.2)
    print ("        A")
    time.sleep(0.5)
    print (color.Magenta + "           AISAH")
    time.sleep(0.3)
    print ("                  TAK")
    time.sleep(0.3)
    print ("                       ADA")
    time.sleep(0.5)
    print ("                            UDANG")
    time.sleep(0.7)
    print ("                                   DIBALIK")
    time.sleep(1.5)
    print (color.Cyan +"                             BATU")
    time.sleep(0.7)
    print ("                         KA")
    time.sleep(0.3)
    print ("                     KA")
    time.sleep(0.2)
    print ("                 KA")
    time.sleep(0.1)
    print ("           KAMU")
    time.sleep(0.3)
    print (color.Yellow +"                 TERCIDUK")
    time.sleep(0.5)
    print ("                           HUJAN")
    time.sleep(0.5)
    print ("                                  BADAI")
    time.sleep(0.5)
    print ("                                         ANGIN")
    time.sleep(0.3)
    print (color.Magenta +"                                    AKU")
    time.sleep(0.5)
    print ("                             SALAH")
    time.sleep(0.5)
    print ("                        DIA")
    time.sleep(0.5)
    print ("                DEKATIKU")
    time.sleep(0.7)
    print ("          TANPA")
    time.sleep(0.7)
    print (color.Cyan +"                 MERASA")
    time.sleep(0.7)
    print ("                         BOSAAAAN...")

    # Selesai
    time.sleep(0.5)
    print (color.Normal + "\nSelesai\n")
    os.system("pause")
    quit()

if __name__ == "__main__":
    main()